FROM openjdk:11-jre

ARG VERSION
ARG VCS_REF

ENV DOER_VERSION $VERSION
ENV DOER_VCS_REF $VCS_REF

ENV DOER_HOME /opt/doer
RUN mkdir $DOER_HOME

WORKDIR $DOER_HOME
COPY ./build/libs/doer-all.jar ./doer.jar
COPY doer.sh doer.sh

RUN chmod +x ./doer.sh && \
    ln -s /opt/doer/doer.sh /usr/bin/doer

EXPOSE 8080
EXPOSE 5005