FROM eclipse-temurin:17

ARG VERSION
ARG VCS_REF
ARG BUILD_DATE
ARG JAR_FILE_NAME="doer.tar"

ENV DOER_VERSION=$VERSION \
  DOER_VCS_REF=$VCS_REF \
  BUILD_DATE=$BUILD_DATE \
  DOER_HOME=/opt/doer-$VERSION \
  LOGBACK_CONFIG_FILE_LOCATION="/opt/doer/conf/container-logback.xml" \
  DOER_JVM_OPTS="-Xms128M -Xmx512M -XX:+UnlockExperimentalVMOptions -XX:+UseZGC"

WORKDIR $DOER_HOME
ADD ${JAR_FILE_NAME} /opt
ADD src/main/resources/container-logback.xml /opt/doer/conf/container-logback.xml
COPY docs/ /opt/doer/docs
ADD doer.sh /opt/doer/doer.sh

LABEL build.git.ref=${VCS_REF} build.date=${BUILD_DATE} \
  org.opencontainers.image.source="https://github.com/sygnowski/doer"
ENTRYPOINT ["bash", "/opt/doer/doer.sh"]

EXPOSE 8080
EXPOSE 5656
