FROM eclipse-temurin:11

ARG VERSION
ARG VCS_REF
ARG BUILD_DATE

ENV DOER_VERSION $VERSION
ENV DOER_VCS_REF $VCS_REF
ENV BUILD_DATE $BUILD_DATE

ENV DOER_HOME /opt/doer

WORKDIR $DOER_HOME
ADD doer.tar /opt

RUN ls -la /opt \
    && ln -s /opt/doer/bin/doer /usr/bin/doer

LABEL build.git.ref=${VCS_REF} build.date=${BUILD_DATE} \
  org.opencontainers.image.source="https://github.com/sygnowski/doer"

EXPOSE 8080
EXPOSE 5656
