{
  "type": "record",
  "name": "KafkaRecord",
  "namespace": "io.s7i",
  "fields": [
    {
      "name": "key",
      "type": [
        "null",
        "bytes"
      ],
      "default": null
    },
    {
      "name": "topic",
      "type": "string"
    },
    {
      "name": "partition",
      "type": "int"
    },
    {
      "name": "offset",
      "type": "long"
    },
    {
      "name": "timestamp",
      "type": "long"
    },
    {
      "name": "value",
      "type": [
        "null",
        "bytes"
      ],
      "default": null
    }
  ]
}
