# Pipeline manifest draft
version: "0.1"
kind: pipeline
pipeline: a | b
spec:
  - name: a
    description: "a" as instance of kafka-dump, making output to doer://pipeline
    manifest:
      file: kdump.yml
  - name: b
    description: "b" as instance of kafka-feed, read from a pipeline
    manifest:
      file: kfeed.yml