
[versions]
cli = "4.7.7"
avro = "1.12.0"
proto = "3.6.1"
grpc = "1.76.0"

[libraries]
cli = { module ="info.picocli:picocli", version.ref = "cli"}
avro = { module = "org.apache.avro:avro", version.ref = "avro"}
proto = { module = "com.google.protobuf:protobuf-java", version.ref = "proto"}
proto-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "proto"}
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-services = { module = "io.grpc:grpc-services", version.ref = "grpc" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
