plugins {
    id "java"
    id 'maven-publish'
}

group = "io.github.s7i"
version = rootProject.file('version').text.trim()

dependencies {
    compileOnly libs.cli, libs.slf4j
}


test {
    useJUnitPlatform()
}


publishing {
    repositories {
        maven {
            name = "Nexus"
            url = uri("http://dwarf.syg:5815/repository/maven-snapshots/")
            allowInsecureProtocol = true
            credentials {
                username = System.getenv("USER_NAME")
                password = System.getenv("USER_PASS")
            }
        }
    }
    publications {
        nexus(MavenPublication) {
            from(components.java)
        }
    }
}
