plugins {
    id "java"
    id 'maven-publish'
}

group = "io.github.s7i"
version = rootProject.file('version').text.trim()

dependencies {
    implementation libs.slf4j,
            libs.proto,
            libs.proto.util,
            libs.grpc.stub,
            libs.grpc.protobuf

    implementation "io.github.s7i.meshtastic.proto:meshtastic-proto:1.0"

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.0'
}


test {
    useJUnitPlatform()
}


publishing {
    repositories {
        maven {
            name = "Nexus"
            url = uri("http://dwarf.syg:5815/repository/maven-snapshots/")
            allowInsecureProtocol = true
            credentials {
                username = System.getenv("USER_NAME")
                password = System.getenv("USER_PASS")
            }
        }
    }
    publications {
        nexus(MavenPublication) {
            from(components.java)
        }
    }
}
